name: Pipeline

on:
    push:
        branches: [main]
    workflow_dispatch:

concurrency:
    group: publish
    cancel-in-progress: true

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    check:
        name: Check
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v7
              with:
                  submodules: "recursive"

            - name: Setup StyLua
              uses: JohnnyMorganz/StyLua@v2.5.2

            - name: Check formatting with StyLua
              run: stylua --check .

    build:
        needs: check
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v7
              with:
                  submodules: "recursive"

            - name: Setup Rokit
              uses: ThatTimothy/setup-rokit@v1

            - name: Install dependencies
              run: rokit install

            - name: Build
              run: lune run scripts/build-artifact

            - name: Upload artifact
              uses: actions/upload-artifact@v7
              with:
                  compression-level: 9
                  if-no-files-found: error
                  overwrite: true
                  path: artifact.rbxl

    deploy:
        needs: build
        name: Publish
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v7
              with:
                  submodules: "recursive"

            - name: Download artifact
              uses: actions/download-artifact@v8

            - name: Publish to Roblox
              id: deployment
              env:
                  API_KEY: ${{ secrets.API_KEY }}
                  PLACE_ID: ${{ secrets.PLACE_ID }}
                  UNIVERSE_ID: ${{ secrets.UNIVERSE_ID }}

              run: lune run scripts/publish-artifact
